# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbad5d1f6d63876279fbd712b163dfb26a7df28678f24152fe1de76336c2960d2b1ba7ba06ca8db96ba15d5e405af23f8d28c6fc8a23d8a41b1e910556c0c333

test:
  secret_key_base: 80c790caaa3a609d0ab370099890c507242ff83538527d5e3b20807f42190e84df25228086b13648f93e16cab5782be6c8cdc11c7fc7edacca37926b6cae00b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
